# Generated by Django 6.0.4 on 2026-04-10 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название автомобиля', max_length=64, verbose_name='Название')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Описание')),
                ('owners', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество владельцев')),
                ('year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
    ]
