# Generated by Django 6.0.4 on 2026-04-10 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000), django.core.validators.MinValueValidator(100)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxLengthValidator(2026)], verbose_name='Год выпуска'),
        ),
    ]
